# Generated by Django 3.2.3 on 2021-07-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut'),
        ),
    ]
